// app_ionic/src/scenes/home/HomePage.vue
<template>
    <v-app-bar>
        <template v-slot:prepend>
            <v-app-bar-title>App Ionic</v-app-bar-title>
        </template>
        <template v-slot:append>
            <span class="mx-2">Simulate Async</span>
            <v-switch hide-details inset color="primary" v-model="isSimulateAsync" />
        </template>

        <template v-slot:extension>
            <v-tabs v-model="tabModel" grow>
                <v-tab value="tab1">Tab 1</v-tab>
                <v-tab value="tab2">Tab 2</v-tab>
            </v-tabs>
        </template>
    </v-app-bar>

    <v-main>
        <v-window v-model="tabModel" class="h-100">
            <v-window-item value="tab1">
                <HomeTabViewContainer title="Tab View 1" :repository="generator"></HomeTabViewContainer>
            </v-window-item>

            <v-window-item value="tab2">
                <HomeTabViewContainer title="Tab View 2" :repository="generator"></HomeTabViewContainer>
            </v-window-item>
        </v-window>
    </v-main>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { HomeDataRepository, HomeDataRandomGeneratorService } from './HomeData';
import HomeTabViewContainer from './HomeTabViewContainer.vue';

const isSimulateAsync = ref(false)
const tabModel = ref(null);

const generator: HomeDataRepository = new HomeDataRandomGeneratorService({
    size: 500,
    minX: 0,
    maxX: 100,
    minY: 0,
    maxY: 10,
    simulateAsync: isSimulateAsync,
});
</script>

// app_react/src/feature/home/HomePage.tsx
import { useState } from 'react';
import { Appbar, DefaultTheme, Switch, Text } from 'react-native-paper';
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
import { HomeDataRepository, HomeDataRandomGeneratorService } from './HomeData';
import HomeTabViewContainer from './HomeTabViewContainer';
import { Dimensions } from 'react-native';

const CHART_MIN_X: number = 0;
const CHART_MAX_X: number = 100;
const CHART_MIN_Y: number = 0;
const CHART_MAX_Y: number = 10;

const Tab = createMaterialTopTabNavigator();

const HomePage = () => {
    const [simulateAsync, setSimulateAsync] = useState(false);

    const generator: HomeDataRepository = new HomeDataRandomGeneratorService({
        size: 500,
        minX: CHART_MIN_X,
        maxX: CHART_MAX_X,
        minY: CHART_MIN_Y,
        maxY: CHART_MAX_Y,
        simulateAsync: simulateAsync,
    });

    return (<>
        <Appbar.Header>
            <Appbar.Content title="App React Native" />
            <Text>Simulate Async</Text>
            <Switch
                value={simulateAsync}
                onValueChange={setSimulateAsync}
            />
        </Appbar.Header>
        <Tab.Navigator
            initialLayout={{
                width: Dimensions.get('window').width,
            }}
            screenOptions={{
                lazy: true,
                tabBarIndicatorStyle: {
                    backgroundColor: DefaultTheme.colors.primary,
                },
              }}
        >
            <Tab.Screen
                name="Tab 1"
                component={TabView1}
                initialParams={{ repository: generator }}
            />
            <Tab.Screen
                name="Tab 2"
                component={TabView2}
                initialParams={{ repository: generator }}
            />
        </Tab.Navigator>
    </>);
}

export default HomePage;

const TabView1 = (props: any) => (
    <HomeTabViewContainer
        title='Tab View 1'
        repository={props.route.params.repository}
    >
        <Text>TODO: Graph 1</Text>
    </HomeTabViewContainer>
);

const TabView2 = (props: any) => (
    <HomeTabViewContainer
        title='Tab View 2'
        repository={props.route.params.repository}
    >
        <Text>TODO: Graph 2</Text>
    </HomeTabViewContainer>
);
